# Generated by Django 4.2.6 on 2023-11-04 01:34

import clients.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('website', clients.models.URLFieldWithPrefix(max_length=200, unique=True)),
                ('industry', models.CharField(max_length=200)),
                ('hq', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('about_client_attachment', models.FileField(upload_to='About_clients/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), clients.models.validate_pdf_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
