# Generated by Django 4.2.6 on 2023-11-04 20:29

import clients.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='about_client_attachment',
            field=models.FileField(blank=True, null=True, upload_to='About_clients/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), clients.models.validate_pdf_extension]),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='active', max_length=8),
        ),
    ]
